### ISSUE TITLE
Error: Cannot find module `use-sync-external-store/shim/with-selector`

### ISSUE THREAD

**Issue by sinnrrr** [NoahZinsmeister/web3-react#379]
Trying to connect web3-react got the following error:
```
Error: Cannot find module '/Users/dmytro/Work/learn/web3-react/packages/example/node_modules/use-sync-external-store/shim/with-selector' imported from /Users/dmytro/Work/learn/web3-react/packages/example/node_modules/@web3-react/core/node_modules/zustand/esm/index.mjs
Did you mean to import use-sync-external-store/shim/with-selector.js?
```

Tried the official example under `packages/example`, but also got the same issue.

**Comment by NoahZinsmeister** [comment]
hm, i haven't seen this before. undoubtedly it's related to the v4 of zustand, which introduces `use-sync-external-store` (see https://github.com/pmndrs/zustand/pull/550)

**Comment by BennyH26** [comment]
Having the same problem, can't figure out a workaround

**Comment by earthtojake** [comment]
+1 having the same problem, works in the example but not in our implementation, can't find a work around

**Comment by michaelxuwu** [comment]
Ran into the same issue with Next.js. I found importing dynamically with no SSR (as in the example) solved this for me.

**Comment by sinnrrr** [comment]
> +1 having the same problem, works in the example but not in our implementation, can't find a work around

Did you try running example yourselves? (on localhost) It’s strange, because official example doesn’t work for me as well as my own implementation.

**Comment by BennyH26** [comment]
> Ran into the same issue with Next.js. I found importing dynamically with no SSR (as in the example) solved this for me.

Using dynamic imports like the example fixed this problem for me. Thank you for the workaround until we can have a more robust solution!

**Comment by fjun99** [comment]
> > Ran into the same issue with Next.js. I found importing dynamically with no SSR (as in the example) solved this for me.
> 
> Using dynamic imports like the example fixed this problem for me. Thank you for the workaround until we can have a more robust solution!

This works for me. bypass this error just like you.

**Comment by BowgartField** [comment]
Is it possible to correct this issue ? this is very annoying

**Comment by mmoderwell** [comment]
@mauver  @BowgartField I believe I've got a solution! Strange to see this work but in `/node_modules/@web3-react/core/node_modules/zustand/esm/index.mjs` you should see the first two lines as:
```js
import { useDebugValue } from 'react';
import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector';
```
Add a `.js` extension to line two so you have:
```js
import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
```
Never great editing stuff in `/node_modules/ but hopefully this works for ya'll as a temporary fix.

**Comment by pedroapfilho** [comment]
Maybe it's the version of Zustand used here? It should be added to the zustand library

**Comment by AzzouQ** [comment]
For those who use `yarn`, you can also add the following to your package.json.
```
  "resolutions": {
    "zustand": "^3.6.9"
  }
```
It will force `@web3-react` to use the stable version of `zustand` instead of the beta (which is likely to cause the bug).

With this or https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1031744585, there's a weird log in nextJS console:

```
error - ../src/index.ts (40:4) @ <unknown>
ReferenceError: window is not defined
null
```

@mmoderwell can you confirm this ? Or those are something on my own.

**Comment by sinnrrr** [comment]
@AzzouQ it seems like ‘web3-react’ does not handle SSR, that is why the components, that make use of ‘web3-react’ are loaded dynamicly without SSR.

**Comment by AzzouQ** [comment]
Indeed, https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1031744585 or https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1032669677 work without dynamic but only in `dev`.
When trying to build with SSR or SSG, `dynamic` is required for the build to not fail..

**Comment by BowgartField** [comment]
> mmoderwell

I already tried this but whitout sucess :/

**Comment by mauver** [comment]
> For those who use `yarn`, you can also add the following to your package.json without modifying anything in `node_modules`.
> 
> ```
>   "resolutions": {
>     "zustand": "^3.6.9"
>   }
> ```
> 
> It will force `@web3-react` to use the stable version of `zustand` instead of the beta (which is likely to cause the bug). Note that if you use another library that rely on zustand, that version will be used too.
> 
> With this or [#379 (comment)](https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1031744585), there's a weird log in nextJS console:
> 
> ```
> error - ../src/index.ts (40:4) @ <unknown>
> ReferenceError: window is not defined
> null
> ```
> 
> @mmoderwell can you confirm this ? Or those are something on my own.

thank you all guys. I solved by adding the zustand package on my package.json.

**Comment by AzzouQ** [comment]
From what I have understand, it's not related to `zustand` but to `@web3-react` and `NextJS`, since using a version of `zustand` that doesn't rely on `use-sync-external-store` makes the error disepear but prevent NextJS to correctly build.

`@web3-react` just doesn't support `SSR`, you won't have this error is using CRA I believe..

**Comment by amsheehan** [comment]
Right. But web3-react takes that version of zustand as a dependency. Even when not doing any SSR the library is unusable in NextJS.

If that is the intended behavior, the library should be renamed to @web3-react-but-not-for-nextjs or something. 😄

**Comment by sinnrrr** [comment]
@amsheehan please, look at the official example, it uses nextjs, you can try to launch it and look at source code

**Comment by AzzouQ** [comment]
I'm actually using some workaround to be able to use those hooks without the inconvenience of importing everything dynamicaly. I've no idea how bad practice it can be tho, but it seems to work as for now...

The main idea is to `dynamic` import only one component that will deconstruct all your hooks (from `initializeConnector` or `getPriorityConnector`). This component will act as a `Provider` and store those hooks inside redux (or zustand) to make them available everywhere without the need to `dynamic` import any other component. It fix the `Error: Cannot find module use-sync-external-store/shim/with-selector` and works with SSR in production.

Will look like this:
```
// HooksProvider.tsx

const HooksProvider: FC = ({ children }) => {
  const dispatch = useAppDispatch();
  const [isReady, setReady] = useState<boolean>(false);

  const priorityConnector = getPriorityConnector(
    [metaMask, metaMaskHooks],
    [walletConnect, walletConnectHooks],
    [network, networkHooks]
  );

  useEffect(() => {
    dispatch(hooksActions.init({ priorityConnector }));
    setReady(true);
  }, [dispatch, priorityConnector]);

  return isReady ? (children as ReactElement) : null;
};

export default HooksProvider;
```
```
// priority.slice.ts

import type { PriorityConnector } from 'src/connectors';

export type PriorityState = {
  priorityConnector: PriorityConnector | undefined;
};

const initialState: PriorityState = {
  priorityConnector: undefined,
};

const prioritySlice = createSlice({
  name: 'priority',
  initialState: initialState,
  reducers: {
    init: (_state, action: PayloadAction<PriorityState>) => action.payload,
    reset: () => initialState,
  },
});

const stateSelector = createSelector(
  ({ priority }: { priority: PriorityState }) => priority,
  (state) => state
);

export const prioritySelectors = {
  getPriorityConnector: createSelector(
    stateSelector,
    (state) => state.priorityConnector as PriorityConnector
  ),
};

export const { actions: priorityActions, reducer: priorityReducer } = prioritySlice;
```
```
// pages/index.tsx

const PriorityExample = dynamic(
  () => import('src/connectors/PriorityExample'),
  { ssr: false }
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        {...}
      </Head>
      <PriorityExample>
        {...} //  Your app (Header, Body, Footer, or whatever)
      </PriorityExample>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: { ... }, 
  };
};

export default Home;
```

**Comment by amsheehan** [comment]
Another solution without having to change the approach to loading components is to override the dependency.

This package forces resolution to a specified version in package-lock.json: https://www.npmjs.com/package/npm-force-resolutions

In your main `package.json` you can then add the following:

```
"scripts": {
  "preinstall": "npx npm-force-resolutions"
},
"resolutions": {
  "zustand": "3.6.9"
}
```

**Comment by pedroapfilho** [comment]
So, the solution would be to create a PR here to:

- Update zustand
- Add checks for window

That's it?

**Comment by pedroapfilho** [comment]
This fixes it: https://github.com/NoahZinsmeister/web3-react/pull/415

The only thing that happens now is the `ReferenceError: window is not defined` that doesn't actually break the build.

**Comment by AzzouQ** [comment]
It's never been a problem with Zustand in the first place (see https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1032682560). Importing component dynamically is enough for not having the zustand error, modifying the version won't solve the build problem since it occur with `resolutions` in package.json.

The problem is related to NextJS especially(see https://github.com/NoahZinsmeister/web3-react/issues/379#issuecomment-1032672580), as this doesn't occur in CRA or else.

**Comment by montanaflynn** [comment]
Just hit this as well, it would be nice if the example project included the fix for dynamic import so people didn't try it out and have to find this issue.

**Comment by AlexandruMares** [comment]
the issue is not fixed

**Comment by tommydangerous** [comment]
Still not fixed

**Comment by Sharathxct** [comment]
used pnpm and it fixed
